In [1]:
import pandas as pd

In [2]:
data_path = "/kaggle/input/datasets/rehanliaqat17/imbd-dataset/IMDB_Dataset.csv"

In [31]:
df = pd.read_csv(data_path)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [32]:
df.shape

(50000, 2)

In [33]:
df = df.head(100)

In [34]:
df.shape

(100, 2)

In [35]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# Lower Case

In [36]:
df["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [37]:
df["review"] = df["review"].str.lower()

In [38]:
df["review"][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# HTML Tags Remover

In [39]:
import re
def remove_html_tags(text):
    pattern = re.compile(r"<.*?>")
    return pattern.sub(r'',text)

In [40]:
text = "<p>This is a <b>GREAT</b> product! <br> I really <i>love</i> it. <a href='https://example.com'>Click here</a></p>"

In [41]:
remove_html_tags(text)

'This is a GREAT product!  I really love it. Click here'

In [42]:
df["review"] = df["review"].apply(remove_html_tags)

In [43]:
df["review"][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# Remove URL

In [62]:
def remove_url(text):
    pattern = re.compile(r"https?://\S+|www\.\S+")
    return pattern.sub(r'',text)

In [63]:
text1 = "Visit https://www.kaggle.com/code/mdnagibmahfuj/data-preprocessing-cleaning-imdb-dataset/edit."

text2 = "Check https://www.kaggle.com for datasets."

text3 = "My website is https://www.amazon.com for shopping."

text4 = "Download from https://github.com/user/project for code."

In [64]:
remove_url(text1)

'Visit '

In [65]:
remove_url(text2)

'Check  for datasets.'

In [66]:
df["review"] = df["review"].apply(remove_url)
df["review"][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

# Punctuation Handling

In [67]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [85]:
def remove_punctuation(text):
    pattern = re.compile(r"[^\w\s]")
    return pattern.sub(r'', text)

In [86]:
text1 = "Hello!!! This product is great, isn't it? #awesome"

remove_punctuation(text1)

'Hello This product is great isnt it awesome'

In [88]:
text2 = "you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. ??? "

In [89]:
remove_punctuation(text2)

'youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go  '

# Chat_Conversion Handle

In [90]:
chat_words = {
    "u": "you",
    "ur": "your",
    "btw": "by the way",
    "lol": "laughing out loud",
    "gr8": "great",
    "thx": "thanks",
    "omg": "oh my god"
}

In [91]:
def chat_conversion(text):
    new_text = []
    for word in text.split():
        new_text.append(chat_words.get(word.lower(), word))
    return " ".join(new_text)

In [92]:
text1 = "u r gr8 btw thx"

chat_conversion(text1)

'you r great by the way thanks'

# Incorrect_Text Handling

In [93]:
from textblob import TextBlob

def correct_text(text):
    return str(TextBlob(text).correct())

In [94]:
text1 = "I realy lov this prodct. It is amzing!"

print(correct_text(text1))

I really love this product. It is amazing!

# Stopwords

In [98]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return " ".join([word for word in text.split() if word.lower() not in stop_words])

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [99]:
df["review"] = df["review"].apply(remove_stopwords)
df["review"][0]

"one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. hardcore, classic use word.it called oz nickname given oswald maximum security state penitentary. focuses mainly emerald city, experimental section prison cells glass fronts face inwards, privacy high agenda. em city home many..aryans, muslims, gangstas, latinos, christians, italians, irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.i would say main appeal show due fact goes shows dare. forget pretty pictures painted mainstream audiences, forget charm, forget romance...oz mess around. first episode ever saw struck nasty surreal, say ready it, watched more, developed taste oz, got accustomed high levels graphic violence. violence, injustice (crooked guards who'll sold nickel, inmates who'll kill order get away it, well mannered, middle class inmates turned prison bitches due lack street skills prison experience) watching oz, may become comfortable uncomfortable viewing....thats get touch darker side."

In [101]:
df["review"] = df["review"].apply(remove_stopwords)
df["review"]

0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
                            ...
95    daniel day-lewis versatile actor alive. englis...
96    guess would originally going least two parts, ...
97    well, like watch bad horror b-movies, cause th...
98    worst movie ever seen, well as, worst probably...
99    mario fan long remember, fond memories playing...
Name: review, Length: 100, dtype: object

# Remove_emoji handle

In [103]:
def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "]+", flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [104]:
text1 = "This product is amazing 😍🔥 I love it ❤️"

print(remove_emoji(text1))

This product is amazing  I love it ❤️

In [105]:
import emoji
print(emoji.demojize('python is 🔥'))

python is :fire:

# Tokenization

In [106]:
from nltk.tokenize import word_tokenize

def word_tokenization(text):
    return word_tokenize(text)

In [107]:
from nltk.tokenize import sent_tokenize

def sentence_tokenization(text):
    return sent_tokenize(text)

In [108]:
text = "This product is amazing! I love it. The quality is great."

print(word_tokenization(text))
print(sentence_tokenization(text))

['This', 'product', 'is', 'amazing', '!', 'I', 'love', 'it', '.', 'The', 'quality', 'is', 'great', '.']
['This product is amazing!', 'I love it.', 'The quality is great.']

# Stemmer

In [109]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

def stemming(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [110]:
text1 = "I am loving this product and the products are amazing"

print(stemming(text1))

i am love thi product and the product are amaz

# Lemmatization

In [111]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

def lemmatization(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...

In [112]:
text1 = "The cats are playing and the dogs are running"

print(lemmatization(text1))

The cat are playing and the dog are running