In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import confusion_matrix
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 255)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
data_path = "/kaggle/input/datasets/rehanliaqat17/imbd-dataset/IMDB_Dataset.csv"

In [3]:
df = pd.read_csv(data_path)
df.head()

,review,sentiment
0,"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of v...",positive
1,"A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen-...",positive
2,"I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...",positive
3,"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br...",negative
4,"Petter Mattei's ""Love in the Time of Money"" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...",positive

In [4]:
df.shape

(50000, 2)

In [5]:
df = df.iloc[:10000]
df.head

<bound method NDFrame.head of                                                                                                                                                                                                                                                               review  \
0     One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of v...
1     A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen-...
2     I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...
3     Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br...
4     Petter Mattei's "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...
5     Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas' performa...
6     I sure would like to see a resurrection of a up dated Seahunt series with the tech they have today it would bring back the kid excitement in me.I grew up on black and white TV and Seahunt with Gunsmoke were my hero's every week.You have my vote for a ...
7     This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decline further to the ...
8     Encouraged by the positive comments about this film on here I was looking forward to watching this film. Bad mistake. I've seen 950+ films and this is truly one of the worst of them - it's awful in almost every way: editing, pacing, storyline, 'acting...
9                                                                                   If you like original gut wrenching laughter you will like this movie. If you are young or old then you will love this movie, hell even my mom liked it.<br /><br />Great Camp!!!
10    Phil the Alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines.<br /><br />At first it was very odd and pretty funny but as the movie progressed I didn't find the jokes or oddness f...
11    I saw this movie when I was about 12 when it came out. I recall the scariest scene was the big bird eating men dangling helplessly from parachutes right out of the air. The horror. The horror.<br /><br />As a young kid going to these cheesy B films on...
12    So im not a big fan of Boll's work but then again not many are. I enjoyed his movie Postal (maybe im the only one). Boll apparently bought the rights to use Far Cry long ago even before the game itself was even finsished. <br /><br />People who have e...
13    The cast played Shakespeare.<br /><br />Shakespeare lost.<br /><br />I appreciate that this is trying to bring Shakespeare to the masses, but why ruin something so good.<br /><br />Is it because 'The Scottish Play' is my favorite Shakespeare? I do not...
14    This a fantastic movie of three prisoners who become famous. One of the actors is george clooney and I'm not a fan but this roll is not bad. Another good thing about the movie is the soundtrack (The man of constant sorrow). I recommand this movie to e...
15    Kind of drawn in by the erotic scenes, only to realize this was one of the most amateurish and unbelievable bits of film I've ever seen. Sort of like a high school film project. What was Rosanna Arquette thinking?? And what was with all those stock ch...
16    Some films just simply should not be remade. This is one of them. In and of itself it is not a bad film. But it fails to capture the flavor and the terror of the 1963 film of the same title. Liam Neeson was excellent as he always is, and most of the c...
17    This movie made it into one of my top 10 most awful movies. Horrible. <br /><br />There wasn't a continuous minute where there wasn't a fight with one monster or another. There was no chance for any character development, they were too busy running fr...
18    I remember this film,it was the first film i had watched at the cinema the picture was dark in places i was very nervous it was back in 74/75 my Dad took me my brother & sister to Newbury cinema in Newbury Berkshire England. I recall the tigers and th...
19    An awful film! It must have been up against some real stinkers to be nominated for the Golden Globe. They've taken the story of the first famous female Renaissance painter and mangled it beyond recognition. My complaint is not that they've taken liber...
20    After the success of Die Hard and it's sequels it's no surprise really that in the 1990s, a glut of 'Die Hard on a .....' movies cashed in on the wrong guy, wrong place, wrong time concept. That is what they did with Cliffhanger, Die Hard on a mountai...
21    I had the terrible misfortune of having to view this "b-movie" in it's entirety.<br /><br />All I have to say is--- save your time and money!!! This has got to be the worst b-movie of all time, it shouldn't even be called a b-movie, more like an f-mov...
22    What an absolutely stunning movie, if you have 2.5 hrs to kill, watch it, you won't regret it, it's too much fun! Rajnikanth carries the movie on his shoulders and although there isn't anything more other than him, I still liked it. The music by A.R.R...
23    First of all, let's get a few things straight here: a) I AM an anime fan- always has been as a matter of fact (I used to watch Speed Racer all the time in Preschool). b) I DO like several B-Movies because they're hilarious. c) I like the Godzilla movi...
24    This was the worst movie I saw at WorldFest and it also received the least amount of applause afterwards! I can only think it is receiving such recognition based on the amount of known actors in the film. It's great to see J.Beals but she's only in th...
25    The Karen Carpenter Story shows a little more about singer Karen Carpenter's complex life. Though it fails in giving accurate facts, and details.<br /><br />Cynthia Gibb (portrays Karen) was not a fine election. She is a good actress , but plays a ver...
26    "The Cell" is an exotic masterpiece, a dizzying trip into not only the vast mind of a serial killer, but also into one of a very talented director. This is conclusive evidence of what can be achieved if human beings unleash their uninhibited imaginati...
27    This film tried to be too many things all at once: stinging political satire, Hollywood blockbuster, sappy romantic comedy, family values promo... the list goes on and on. It failed miserably at all of them, but there was enough interest to keep me fr...
28    This movie was so frustrating. Everything seemed energetic and I was totally prepared to have a good time. I at least thought I'd be able to stand it. But, I was wrong. First, the weird looping? It was like watching "America's Funniest Home Videos". T...
29    'War movie' is a Hollywood genre that has been done and redone so many times that clichéd dialogue, rehashed plot and over-the-top action sequences seem unavoidable for any conflict dealing with large-scale combat. Once in a while, however, a war movi...
30    Taut and organically gripping, Edward Dmytryk's Crossfire is a distinctive suspense thriller, an unlikely "message" movie using the look and devices of the noir cycle.<br /><br />Bivouacked in Washington, DC, a company of soldiers cope with their rest...
31    "Ardh Satya" is one of the finest film ever made in Indian Cinema. Directed by the great director Govind Nihalani, this one is the most successful Hard Hitting Parallel Cinema which also turned out to be a Commercial Success. Even today, Ardh Satya is...
32    My first exposure to the Templarios & not a good one. I was excited to find this title among the offerings from Anchor Bay Video, which has brought us other cult classics such as "Spider Baby". The print quality is excellent, but this alone can't hide...
33    One of the most significant quotes from the entire film is pronounced halfway through by the protagonist, the mafia middle-man Titta Di Girolamo, a physically non-descript, middle-aged man originally from Salerno in Southern Italy. When we're introduc...
34    I watched this film not really expecting much, I got it in a pack of 5 films, all of which were pretty terrible in their own way for under a fiver so what could I expect? and you know what I was right, they were all terrible, this movie has a few (and...
35    I bought this film at Blockbuster for $3.00, because it sounded interesting (a bit Ranma-esque, with the idea of someone dragging around a skeleton), because there was a cute girl in a mini-skirt on the back, and because there was a Restricted Viewing...
36    The plot is about the death of little children. Hopper is the one who has to investigate the killings. During the movie it appears that he has some troubles with his daughter. In the end the serial killer get caught. That's it. But before you find out...
37    Ever watched a movie that lost the plot? Well, this didn't even really have one to begin with.<br /><br />Where to begin? The achingly tedious scenes of our heroine sitting around the house with actually no sense of menace or even foreboding created e...
38    Okay, so this series kind of takes the route of 'here we go again!' Week in, week out David Morse's character helps out his ride who is in a bit of a pickle - but what's wrong with that!? David Morse is one of the greatest character actors out there, ...
39    After sitting through this pile of dung, my husband and I wondered whether it was actually the product of an experiment to see whether a computer program could produce a movie. It was that listless and formulaic. But the U.S. propaganda thrown in your...
40    It had all the clichés of movies of this type and no substance. The plot went nowhere and at the end of the movie I felt like a sucker for watching it. The production was good; however, the script and acting were B-movie quality. The casting was poor ...
41    This movie is based on the book, "A Many Splendored Thing" by Han Suyin and tackles issues of race relations between Asians and Whites, a topic that comes from Han's personal experiences as an Eurasian growing up in China. That background, and the bea...
42    Of all the films I have seen, this one, The Rage, has got to be one of the worst yet. The direction, LOGIC, continuity, changes in plot-script and dialog made me cry out in pain. "How could ANYONE come up with something so crappy"? Gary Busey is know ...
43    I had heard good things about "States of Grace" and came in with an open mind. I thought that "God's Army" was okay, and I thought that maybe Dutcher had improved and matured as a filmmaker. The film began with some shaky acting, and I thought, "well,...
44    This movie struck home for me. Being 29, I remember the '80's and my father working in a factory. I figured, if I worked hard too, if I had pride and never gave up I too could have the American Dream, the house, a few kids, a car all to call my own. I...
45    As a disclaimer, I've seen the movie 5-6 times in the last 15 years, and I only just saw the musical this week. This allowed me to judge the movie without being tainted by what was or wasn't in the musical (however, it tainted me when I watched the mu...
46    Protocol is an implausible movie whose only saving grace is that it stars Goldie Hawn along with a good cast of supporting actors. The story revolves around a ditzy cocktail waitress who becomes famous after inadvertently saving the life of an Arab di...
47    How this film could be classified as Drama, I have no idea. If I were John Voight and Mary Steenburgen, I would be trying to erase this from my CV. It was as historically accurate as Xena and Hercules. Abraham and Moses got melded into Noah. Lot, Abra...
48    Preston Sturgis' THE POWER AND THE GLORY was unseen by the public for nearly twenty or thirty years until the late 1990s when it resurfaced and even showed up on television. In the meantime it had gained in notoriety because Pauline Kael's THE CITIZEN...
49    Average (and surprisingly tame) Fulci giallo which means it's still quite bad by normal standards, but redeemed by its solid build-up and some nice touches such as a neat time twist on the issues of visions and clairvoyance.<br /><br />The genre's wel...
50    Return to the 36th Chamber is one of those classic Kung-Fu movies which Shaw produces back in the 70s and 80s, whose genre is equivalent to the spaghetti westerns of Hollywood, and the protagonist Gordon Liu, the counterpart to the western's Clint Eas...
51    ***SPOILERS*** All too, in real life as well as in the movies, familiar story that happens to many young men who are put in a war zone with a gun, or rifle, in their hands. The case of young and innocent, in never handling or firing a gun, Jimmy Davis...
52    Bela Lugosi appeared in several of these low budget chillers for Monogram Studios in the 1940's and The Corpse Vanishes is one of the better ones.<br /><br />Bela plays a mad scientist who kidnaps young brides and kills them and then extracts fluid fr...
53    I cannot believe I enjoyed this as much as I did. The anthology stories were better than par, but the linking story and its surprise ending hooked me. Alot of familiar faces will keep you asking yourself "where I have I seen them before?" Forget the r...
54    The 33 percent of the nations nitwits that still support W. Bush would do well to see this movie, which shows the aftermath of the French revolution and the terror of 1794 as strikingly similar to the post 9/11 socio-political landscape. Maybe then th...
55    As someone has already mentioned on this board, it's very difficult to make a fake documentary. It requires tremendous skill, pacing, patience, directorial 'distance,' a plausible premise, a narrative 'flow,' and REALLY believable acting (aka GREAT ac...
56    The Hills Have Eyes II is what you would expect it to be and nothing more. Of course it's not going to be an Oscar nominated film, it's just pure entertainment which you can just lose yourself in for 90 minutes.<br /><br />The plot is basically about ...
57    I laughed all the way through this rotten movie. It's so unbelievable. A woman leaves her husband after many years of marriage, has a breakdown in front of a real estate office. What happens? The office manager comes outside and offers her a job!!! Hi...
58    NO SPOILERS!!<br /><br />After Hitchcock's successful first American film, Rebecca based upon Daphne DuMarier's lush novel of gothic romance and intrigue, he returned to some of the more familiar themes of his early British period - mistaken identity ...
59    I just watched The Dresser this evening, having only seen it once before, about a dozen years ago.<br /><br />It's not a "big" movie, and doesn't try to make a big splash, but my God, the brilliance of the two leads leaves me just about speechless. Al...
60    What happened? What we have here is basically a solid and plausible premise and with a decent and talented cast, but somewhere the movie loses it. Actually, it never really got going. There was a little excitement when we find out that Angie is not re...
61    I've just watched Fingersmith, and I'm stunned to see the 8/10 average rating for the show.<br /><br />Not only was the plot was difficult to follow, but it seems character development was randomly applied.<br /><br />The actors were adequate, but in ...
62    So let's begin!)))<br /><br />The movie itself is as original as Cronenberg's movies would usually appear...<br /><br />My intention to see it was certainly JJL being one of my favourite actresses. She is as lovely as usual, this cutie!<br /><br />I w...
63    Besides being boring, the scenes were oppressive and dark. The movie tried to portray some kind of moral, but fell flat with its message. What were the redeeming qualities?? On top of that, I don't think it could make librarians look any more unglamor...
64    An unmarried woman named Stella (Bette Midler) gets pregnant by a wealthy man (Stephen Collins). He offers to marry her out of a sense of obligation but she turns him down flat and decides to raise the kid on her own. Things go OK until the child name...
65    DON'T TORTURE A DUCKLING is one of Fulci's earlier (and honestly, in terms of story-line, better...) films - and although not the typical "bloodbath" that Fulci is known for - this is still a very unique and enjoyable film.<br /><br />The story surrou...
66    Busty beauty Stacie Randall plays PVC clad, bad-ass bitch Alexandra, the faithful acolyte of Faust, an evil entity trapped in hell. Determined to free her master, the malevolent minx breaks into a warehouse to steal a magical gem vital to her success;...
67    I really like Salman Kahn so I was really disappointed when I seen this movie. It didn't have much of a plot and what they did have was not that appealing. Salman however did look good in the movie looked young and refreshed but was worth the price of...
68    I'm not sure why the producers needed to trade on the name of a somewhat successful movie franchise because the title suggests that it is a sequel to the first three movies..which it is not. Even though Marques Houston did appear in "HP3", he played a...
69    This film laboured along with some of the most predictable story lines and shallow characters ever seen. The writer obviously bought the playbook "How to write a space disaster movie" and followed it play by play. In particular, the stereo-typical use...
70    Caddyshack Two is a good movie by itself but compared to the original it cant stack up. Robert Stack is a horrible replacement for Ted Knight and Jackie Mason, while funny just cant compete with Rodney Dangerfield. Ty Webb is funny, being the only cha...
71    Honestly - this short film sucks. the dummy used in the necro scene is pretty well made but still phony enough looking to ruin the viewing experience. the Unearthed DVD is crisp and clear and I haven't made up my mind if this helps or hinders it. If t...
72    I thought that Mukhsin has been wonderfully written. Its not just about entertainment. There's tonnes of subtle messages that i think Yasmin was trying to bring across. And yes, it might be confusing to some of you(especially if you didn't watch Sepet...
73    I am not a golf fan by any means. On May 26 about 10:30 PM the movie started with a scene in the late 1800's. Old movies I like but not golf however, within the first scene a young boy (Harry Vardon) is awaken by the voices of men. He goes outside to ...
74    Upon viewing Tobe Hooper's gem, Crocodile, in 2000, I developed a great interest in the college/crocodile niche of the exploitation/monster genre. I look forward to a wayward producer to follow up with several sequels to these delightful bonbons of ca...

In [6]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [7]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(17)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

**Basic Preprocessing**
* Remove tags-HTML
* Lower case
* Remove stopwords

In [13]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
    return cleaned_text

In [14]:
df['review'] = df['review'].apply(remove_tags)
df.head()

,review,sentiment
0,"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, whi...",positive
1,"A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only ...",positive
2,"I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...",positive
3,"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.OK, first of al...",negative
4,"Petter Mattei's ""Love in the Time of Money"" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...",positive

In [15]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [16]:
df['review'] = df['review'].apply(lambda x:x.lower())
df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [17]:
from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')
sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:"".join(x))

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:
df['review'][0]

"onereviewersmentionedwatching1ozepisodehooked.right,exactlyhappenedme.thefirstthingstruckozbrutalityunflinchingscenesviolence,setrightwordgo.trustme,showfaintheartedtimid.showpullspunchesregardsdrugs,sexviolence.hardcore,classicuseword.itcalledoznicknamegivenoswaldmaximumsecuritystatepenitentary.focusesmainlyemeraldcity,experimentalsectionprisoncellsglassfrontsfaceinwards,privacyhighagenda.emcityhomemany..aryans,muslims,gangstas,latinos,christians,italians,irishmore....soscuffles,deathstares,dodgydealingsshadyagreementsneverfaraway.iwouldsaymainappealshowduefactgoesshowsdare.forgetprettypicturespaintedmainstreamaudiences,forgetcharm,forgetromance...ozmessaround.firstepisodeeversawstrucknastysurreal,sayreadyit,watchedmore,developedtasteoz,gotaccustomedhighlevelsgraphicviolence.violence,injustice(crookedguardswho'llsoldnickel,inmateswho'llkillordergetawayit,wellmannered,middleclassinmatesturnedprisonbitchesduelackstreetskillsprisonexperience)watchingoz,maybecomecomfortableuncomfortableviewing....thatsgettouchdarkerside."

In [19]:
df.head()

,review,sentiment
0,"onereviewersmentionedwatching1ozepisodehooked.right,exactlyhappenedme.thefirstthingstruckozbrutalityunflinchingscenesviolence,setrightwordgo.trustme,showfaintheartedtimid.showpullspunchesregardsdrugs,sexviolence.hardcore,classicuseword.itcalledoznickn...",positive
1,"wonderfullittleproduction.filmingtechniqueunassuming-old-time-bbcfashiongivescomforting,sometimesdiscomforting,senserealismentirepiece.actorsextremelywellchosen-michaelsheen""hasgotpolari""voicespattoo!trulyseeseamlesseditingguidedreferenceswilliams'dia...",positive
2,"thoughtwonderfulwayspendtimehotsummerweekend,sittingairconditionedtheaterwatchinglight-heartedcomedy.plotsimplistic,dialoguewittycharacterslikable(evenwellbreadsuspectedserialkiller).maydisappointedrealizematchpoint2:riskaddiction,thoughtproofwoodyall...",positive
3,"basicallythere'sfamilylittleboy(jake)thinksthere'szombiecloset&parentsfightingtime.thismovieslowersoapopera...suddenly,jakedecidesbecomerambokillzombie.ok,firstgoingmakefilmmustdecidethrillerdrama!dramamoviewatchable.parentsdivorcing&arguinglikerealli...",negative
4,"pettermattei's""lovetimemoney""visuallystunningfilmwatch.mr.matteioffersusvividportraithumanrelations.movieseemstellingusmoney,powersuccesspeopledifferentsituationsencounter.variationarthurschnitzler'splaytheme,directortransfersactionpresenttimenewyorkd...",positive

In [20]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [22]:
X.head()

                                                                                                                                                                                                                                                           review
0  onereviewersmentionedwatching1ozepisodehooked.right,exactlyhappenedme.thefirstthingstruckozbrutalityunflinchingscenesviolence,setrightwordgo.trustme,showfaintheartedtimid.showpullspunchesregardsdrugs,sexviolence.hardcore,classicuseword.itcalledoznickn...
1  wonderfullittleproduction.filmingtechniqueunassuming-old-time-bbcfashiongivescomforting,sometimesdiscomforting,senserealismentirepiece.actorsextremelywellchosen-michaelsheen"hasgotpolari"voicespattoo!trulyseeseamlesseditingguidedreferenceswilliams'dia...
2  thoughtwonderfulwayspendtimehotsummerweekend,sittingairconditionedtheaterwatchinglight-heartedcomedy.plotsimplistic,dialoguewittycharacterslikable(evenwellbreadsuspectedserialkiller).maydisappointedrealizematchpoint2:riskaddiction,thoughtproofwoodyall...
3  basicallythere'sfamilylittleboy(jake)thinksthere'szombiecloset&parentsfightingtime.thismovieslowersoapopera...suddenly,jakedecidesbecomerambokillzombie.ok,firstgoingmakefilmmustdecidethrillerdrama!dramamoviewatchable.parentsdivorcing&arguinglikerealli...
4  pettermattei's"lovetimemoney"visuallystunningfilmwatch.mr.matteioffersusvividportraithumanrelations.movieseemstellingusmoney,powersuccesspeopledifferentsituationsencounter.variationarthurschnitzler'splaytheme,directortransfersactionpresenttimenewyorkd...

In [23]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
5       positive
6       positive
7       negative
8       negative
9       positive
10      negative
11      negative
12      negative
13      negative
14      positive
15      negative
16      positive
17      negative
18      positive
19      negative
20      positive
21      negative
22      positive
23      negative
24      negative
25      positive
26      positive
27      negative
28      negative
29      positive
30      positive
31      positive
32      negative
33      positive
34      negative
35      negative
36      negative
37      negative
38      positive
39      negative
40      negative
41      positive
42      negative
43      negative
44      positive
45      positive
46      negative
47      negative
48      positive
49      negative
50      positive
51      positive
52      positive
53      positive
54      negative
55      negative
56      negative
57      negative
58      positive
59      positive
60      negative
61      negative
62      positive
63      negative
64      negative
65      positive
66      negative
67      negative
68      negative
69      negative
70      negative
71      negative
72      positive
73      positive
74      negative
75      positive
76      positive
77      negative
78      negative
79      positive
80      positive
81      negative
82      negative
83      negative
84      negative
85      negative
86      negative
87      negative
88      negative
89      negative
90      positive
91      negative
92      positive
93      positive
94      negative
95      positive
96      negative
97      negative
98      negative
99      positive
100     positive
101     negative
102     positive
103     positive
104     negative
105     positive
106     positive
107     negative
108     positive
109     positive
110     negative
111     negative
112     negative
113     positive
114     positive
115     positive
116     positive
117     negative
118     negative
119     negative
120     positive
121     positive
122     negative
123     negative
124     positive
125     negative
126     negative
127     negative
128     positive
129     positive
130     positive
131     positive
132     negative
133     negative
134     negative
135     negative
136     positive
137     negative
138     positive
139     negative
140     negative
141     negative
142     negative
143     positive
144     negative
145     positive
146     positive
147     positive
148     negative
149     negative
150     positive
151     negative
152     negative
153     positive
154     negative
155     negative
156     negative
157     positive
158     negative
159     positive
160     positive
161     negative
162     negative
163     negative
164     positive
165     negative
166     positive
167     negative
168     negative
169     negative
170     negative
171     negative
172     positive
173     positive
174     negative
175     negative
176     positive
177     negative
178     positive
179     negative
180     positive
181     negative
182     negative
183     negative
184     negative
185     negative
186     positive
187     negative
188     positive
189     negative
190     positive
191     positive
192     positive
193     positive
194     negative
195     negative
196     negative
197     negative
198     positive
199     negative
200     negative
201     positive
202     positive
203     positive
204     negative
205     positive
206     negative
207     negative
208     positive
209     positive
210     negative
211     negative
212     negative
213     positive
214     negative
215     positive
216     positive
217     negative
218     positive
219     negative
220     negative
221     positive
222     positive
223     negative
224     positive
225     negative
226     positive
227     positive
228     positive
229     positive
230     negative
231     positive
232     positive
233     positive
234     positive
235     positive
236     positive
237     negative
238     positive
239     negative
240     negative
241     positive
242     negative
243     positive
244     negative
245     positive
246     negative
247     negative
248     positive
249     negative
250     negative
251     negative
252     negative
253     negative
254     positive
255     negative
256     negative
257     negative
258     positive
259     positive
260     positive
261     negative
262     negative
263     negative
264     negative
265     positive
266     negative
267     negative
268     negative
269     positive
270     negative
271     positive
272     positive
273     positive
274     negative
275     positive
276     negative
277     positive
278     negative
279     positive
280     positive
281     negative
282     negative
283     negative
284     positive
285     negative
286     positive
287     positive
288     positive
289     positive
290     positive
291     positive
292     positive
293     positive
294     positive
295     negative
296     negative
297     positive
298     positive
299     positive
300     negative
301     negative
302     positive
303     positive
304     positive
305     positive
306     positive
307     negative
308     negative
309     negative
310     positive
311     negative
312     negative
313     negative
314     negative
315     negative
316     positive
317     positive
318     positive
319     negative
320     positive
321     positive
322     negative
323     positive
324     negative
325     positive
326     positive
327     negative
328     positive
329     positive
330     negative
331     positive
332     positive
333     positive
334     positive
335     negative
336     positive
337     positive
338     negative
339     negative
340     negative
341     positive
342     negative
343     positive
344     negative
345     negative
346     negative
347     positive
348     negative
349     negative
350     positive
351     negative
352     negative
353     positive
354     negative
355     negative
356     positive
357     negative
358     negative
359     negative
360     positive
361     negative
362     positive
363     positive
364     positive
365     negative
366     negative
367     negative
368     positive
369     positive
370     positive
371     positive
372     negative
373     positive
374     positive
375     negative
376     positive
377     negative
378     positive
379     negative
380     negative
381     positive
382     positive
383     negative
384     negative
385     negative
386     negative
387     positive
388     positive
389     positive
390     positive
391     negative
392     positive
393     positive
394     positive
395     negative
396     negative
397     positive
398     negative
399     positive
400     positive
401     negative
402     negative
403     positive
404     positive
405     negative
406     positive
407     positive
408     negative
409     positive
410     negative
411     positive
412     negative
413     negative
414     negative
415     negative
416     negative
417     positive
418     negative
419     negative
420     negative
421     negative
422     negative
423     positive
424     negative
425     positive
426     positive
427     positive
428     negative
429     positive
430     negative
431     negative
432     negative
433     positive
434     negative
435     positive
436     positive
437     positive
438     positive
439     positive
440     negative
441     positive
442     negative
443     negative
444     negative
445     negative
446     negative
447     positive
448     negative
449     negative
450     positive
451     positive
452     negative
453     positive
454     positive
455     positive
456     negative
457     positive
458     negative
459     negative
460     positive
461     positive
462     negative
463     negative
464     negative
465     positive
466     positive
467     positive
468     negative
469     positive
470     negative
471     negative
472     negative
473     negative
474     positive
475     positive
476     positive
477     negative
478     negative
479     positive
480     negative
481     positive
482     negative
483     positive
484     positive
485     negative
486     negative
487     positive
488     positive
489     negative
490     negative
491     positive
492     positive
493     positive
494     positive
495     negative
496     negative
497     negative
498     negative
499     positive
500     negative
501     positive
502     positive
503     negative
504     positive
505     positive
506     negative
507     positive
508     negative
509     positive
510     negative
511     negative
512     negative
513     negative
514     negative
515     positive
516     negative
517     positive
518     positive
519     negative
520     negative
521     positive
522     positive
523     negative
524     negative
525     negative
526     positive
527     negative
528     positive
529     negative
530     negative
531     positive
532     positive
533     positive
534     positive
535     negative
536     negative
537     negative
538     negative
539     positive
540     positive
541     negative
542     negative
543     negative
544     negative
545     negative
546     negative
547     positive
548     negative
549     positive
550     negative
551     negative
552     positive
553     negative
554     negative
555     negative
556     positive
557     positive
558     positive
559     negative
560     negative
561     negative
562     negative
563     negative
564     positive
565     negative
566     positive
567     positive
568     positive
569     negative
570     positive
571     positive
572     positive
573     negative
574     negative
575     negative
576     negative
577     negative
578     negative
579     positive
580     positive
581     negative
582     positive
583     negative
584     positive
585     positive
586     positive
587     negative
588     negative
589     negative
590     positive
591     negative
592     positive
593     positive
594     positive
595     positive
596     negative
597     positive
598     positive
599     negative
600     positive
601     positive
602     positive
603     negative
604     negative
605     positive
606     positive
607     positive
608     positive
609     positive
610     negative
611     positive
612     negative
613     negative
614     positive
615     negative
616     positive
617     negative
618     positive
619     negative
620     positive
621     positive
622     positive
623     negative
624     positive
625     negative
626     positive
627     negative
628     positive
629     positive
630     negative
631     positive
632     positive
633     positive
634     positive
635     negative
636     negative
637     negative
638     positive
639     positive
640     negative
641     positive
642     negative
643     positive
644     negative
645     positive
646     negative
647     positive
648     positive
649     negative
650     positive
651     negative
652     negative
653     positive
654     negative
655     negative
656     positive
657     positive
658     positive
659     negative
660     negative
661     positive
662     positive
663     positive
664     positive
665     negative
666     positive
667     positive
668     negative
669     positive
670     positive
671     negative
672     negative
673     negative
674     negative
675     negative
676     positive
677     positive
678     negative
679     negative
680     positive
681     negative
682     positive
683     positive
684     negative
685     negative
686     positive
687     negative
688     negative
689     positive
690     positive
691     negative
692     negative
693     positive
694     positive
695     negative
696     positive
697     positive
698     positive
699     negative
700     negative
701     positive
702     negative
703     positive
704     positive
705     negative
706     positive
707     positive
708     negative
709     negative
710     positive
711     positive
712     positive
713     positive
714     positive
715     negative
716     negative
717     negative
718     negative
719     negative
720     negative
721     negative
722     positive
723     positive
724     positive
725     negative
726     positive
727     positive
728     positive
729     negative
730     positive
731     negative
732     positive
733     positive
734     positive
735     positive
736     negative
737     positive
738     negative
739     positive
740     negative
741     positive
742     negative
743     positive
744     negative
745     positive
746     positive
747     positive
748     negative
749     positive
750     positive
751     negative
752     negative
753     negative
754     negative
755     positive
756     negative
757     negative
758     negative
759     positive
760     positive
761     negative
762     positive
763     negative
764     positive
765     negative
766     negative
767     negative
768     negative
769     negative
770     negative
771     negative
772     positive
773     positive
774     negative
775     positive
776     negative
777     negative
778     positive
779     negative
780     positive
781     positive
782     positive
783     negative
784     negative
785     negative
786     positive
787     positive
788     negative
789     positive
790     positive
791     negative
792     positive
793     positive
794     negative
795     positive
796     positive
797     positive
798     negative
799     positive
800     positive
801     positive
802     positive
803     positive
804     positive
805     negative
806     positive
807     positive
808     positive
809     negative
810     negative
811     positive
812     positive
813     positive
814     positive
815     negative
816     positive
817     positive
818     positive
819     negative
820     positive
821     positive
822     positive
823     positive
824     negative
825     positive
826     positive
827     negative
828     negative
829     negative
830     negative
831     positive
832     positive
833     negative
834     negative
835     positive
836     negative
837     positive
838     positive
839     positive
840     positive
841     negative
842     positive
843     negative
844     positive
845     negative
846     positive
847     negative
848     negative
849     positive
850     positive
851     negative
852     positive
853     positive
854     negative
855     positive
856     positive
857     negative
858     positive
859     negative
860     positive
861     negative
862     negative
863     positive
864     positive
865     negative
866     positive
867     positive
868     negative
869     positive
870     negative
871     positive
872     positive
873     positive
874     positive
875     negative
876     positive
877     negative
878     negative
879     negative
880     negative
881     negative
882     negative
883     negative
884     positive
885     negative
886     negative
887     positive
888     positive
889     positive
890     positive
891     positive
892     positive
893     negative
894     positive
895     positive
896     positive
897     positive
898     negative
899     negative
900     positive
901     negative
902     negative
903     negative
904     negative
905     negative
906     positive
907     positive
908     positive
909     positive
910     positive
911     positive
912     negative
913     negative
914     negative
915     positive
916     negative
917     positive
918     positive
919     positive
920     positive
921     negative
922     negative
923     positive
924     negative
925     positive
926     negative
927     negative
928     positive
929     positive
930     positive
931     positive
932     negative
933     negative
934     negative
935     positive
936     negative
937     negative
938     negative
939     positive
940     negative
941     positive
942     negative
943     positive
944     positive
945     negative
946     positive
947     positive
948     positive
949     positive
950     positive
951     positive
952     positive
953     positive
954     positive
955     positive
956     negative
957     positive
958     negative
959     negative
960     positive
961     positive
962     positive
963     positive
964     positive
965     negative
966     negative
967     positive
968     positive
969     negative
970     negative
971     negative
972     positive
973     negative
974     negative
975     negative
976     negative
977     negative
978     negative
979     positive
980     negative
981     negative
982     negative
983     negative
984     positive
985     positive
986     positive
987     positive
988     positive
989     negative
990     negative
991     negative
992     positive
993     negative
994     positive
995     positive
996     negative
997     negative
998     negative
999     negative
1000    negative
1001    negative
1002    negative
1003    positive
1004    positive
1005    negative
1006    negative
1007    positive
1008    positive
1009    positive
1010    positive
1011    positive
1012    negative
1013    negative
1014    positive
1015    positive
1016    positive
1017    negative
1018    positive
1019    negative
1020    negative
1021    positive
1022    negative
1023    positive
1024    negative
1025    negative
1026    positive
1027    negative
1028    negative
1029    positive
1030    negative
1031    negative
1032    negative
1033    negative
1034    negative
1035    negative
1036    positive
1037    positive
1038    positive
1039    positive
1040    positive
1041    positive
1042    positive
1043    negative
1044    positive
1045    positive
1046    positive
1047    positive
1048    positive
1049    positive
1050    negative
1051    negative
1052    positive
1053    positive
1054    positive
1055    positive
1056    positive
1057    negative
1058    negative
1059    negative
1060    negative
1061    positive
1062    negative
1063    negative
1064    negative
1065    negative
1066    positive
1067    positive
1068    negative
1069    positive
1070    negative
1071    negative
1072    positive
1073    negative
1074    negative
1075    negative
1076    positive
1077    negative
1078    positive
1079    negative
1080    positive
1081    positive
1082    negative
1083    negative
1084    positive
1085    positive
1086    positive
1087    positive
1088    negative
1089    negative
1090    positive
1091    negative
1092    negative
1093    negative
1094    positive
1095    negative
1096    negative
1097    negative
1098    positive
1099    negative
1100    positive
1101    negative
1102    negative
1103    negative
1104    negative
1105    positive
1106    positive
1107    positive
1108    negative
1109    positive
1110    positive
1111    positive
1112    negative
1113    positive
1114    negative
1115    negative
1116    negative
1117    negative
1118    positive
1119    negative
1120    negative
1121    negative
1122    positive
1123    negative
1124    positive
1125    positive
1126    positive
1127    positive
1128    negative
1129    negative
1130    negative
1131    positive
1132    negative
1133    positive
1134    positive
1135    positive
1136    negative
1137    positive
1138    positive
1139    positive
1140    negative
1141    positive
1142    negative
1143    positive
1144    positive
1145    positive
1146    positive
1147    positive
1148    positive
1149    negative
1150    positive
1151    positive
1152    positive
1153    positive
1154    positive
1155    negative
1156    positive
1157    negative
1158    positive
1159    positive
1160    positive
1161    positive
1162    negative
1163    positive
1164    positive
1165    positive
1166    positive
1167    negative
1168    positive
1169    positive
1170    positive
1171    positive
1172    positive
1173    negative
1174    positive
1175    positive

In [24]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [25]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [30]:
X_train.shape

(7986, 1)

In [31]:
X_test.shape

(1997, 1)

In [35]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [38]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.fit_transform(X_test['review']).toarray()

In [39]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [53]:
print(type(X_train))
print(type(y_train))

print("X_train shape:", X_train.shape if hasattr(X_train, 'shape') else len(X_train))
print("y_train shape:", y_train.shape if hasattr(y_train, 'shape') else len(y_train))

print("X_train_bow shape:", X_train_bow.shape)
print("y_train shape:", y_train.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
X_train shape: (7986, 1)
y_train shape: (7986,)
X_train_bow shape: (1, 1)
y_train shape: (7986,)

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Convert to 1D
X_train = X_train.squeeze()
X_test = X_test.squeeze()
y_train = y_train.squeeze()
y_test = y_test.squeeze()

# 2. BOW - same vectorizer
bow = CountVectorizer()

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

# 3. GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow.toarray(), y_train)

# 4. Prediction
y_pred = gnb.predict(X_test_bow.toarray())

# 5. Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# 6. Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# 7. Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.642463695543315

Confusion Matrix:
[[455 497]
 [217 828]]

Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.48      0.56       952
           1       0.62      0.79      0.70      1045

    accuracy                           0.64      1997
   macro avg       0.65      0.64      0.63      1997
weighted avg       0.65      0.64      0.63      1997

In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Random Forest Classifier
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train
rf.fit(X_train_bow, y_train)

# Prediction
y_pred = rf.predict(X_test_bow)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.6499749624436655

Confusion Matrix:
[[439 513]
 [186 859]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.46      0.56       952
           1       0.63      0.82      0.71      1045

    accuracy                           0.65      1997
   macro avg       0.66      0.64      0.63      1997
weighted avg       0.66      0.65      0.64      1997

In [59]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

rf = RandomForestClassifier()
rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.6359539308963446

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# N-gram Count Vectorizer
cv = CountVectorizer(
    max_features=3000,
    ngram_range=(1, 2)
)

# Transform data
X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

# Random Forest Classifier
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train
rf.fit(X_train_bow, y_train)

# Prediction
y_pred = rf.predict(X_test_bow)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.6314471707561342

Confusion Matrix:
[[595 357]
 [379 666]]

Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.62      0.62       952
           1       0.65      0.64      0.64      1045

    accuracy                           0.63      1997
   macro avg       0.63      0.63      0.63      1997
weighted avg       0.63      0.63      0.63      1997

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=3000)

# Transform data
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

# Random Forest Classifier
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

# Train
rf.fit(X_train_tfidf, y_train)

# Prediction
y_pred = rf.predict(X_test_tfidf)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.6459689534301453

Confusion Matrix:
[[601 351]
 [356 689]]

Classification Report:
              precision    recall  f1-score   support

           0       0.63      0.63      0.63       952
           1       0.66      0.66      0.66      1045

    accuracy                           0.65      1997
   macro avg       0.65      0.65      0.65      1997
weighted avg       0.65      0.65      0.65      1997